#!/bin/sh
set -x
groupadd haproxy
useradd hapocer1
gpasswd -a hapocer1 haproxy
APP=OCE
PLT=REC1
PID=/var/run/haproxy$APP$PLT.pid
touch $PID
mkdir /HOME/haproxy/product/1.3.22/bin/ -p && ln -sf $(which haproxy) /HOME/haproxy/product/1.3.22/bin/haproxy
/HOME/hapadm/OCE/scripts/hapctlOCEREC1 reload; sleep 2;
#haproxy -f /HOME/hapadm/$APP/Config/hap$APP$PLT.conf -p $PID -sf $(cat $PID)