#!/bin/sh
#       Guillaume PENIN - le 30/04/2009
#       syntaxe : HAP_KILL [-USR1|-HUP|-0|-TTOU|-TTIN] <fichier_pid>

SIGNAL=""

if [ "$1" = "-USR1" -o "$1" = "-HUP" -o "$1" = "-0" -o "$1" = "-TTOU" -o "$1" = "-TTIN" ] ;then
        SIGNAL="$1"
        shift
fi

FILE=$1

[ -n $FILE ] && [ -f $FILE ] && PID=`cat $FILE`
[ -z $PID ] && exit 2

if [ `ps -ef | grep -v grep | grep "$PID.*haproxy" | wc -l` -ne 0 ];then
        kill $SIGNAL $PID
else
        exit 3
fi
