server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  requestLog:
    appenders:
      - type: console
        threshold: WARN
threads: 20
repository:
  host: localhost
  port: 8500
  minGeneratedPort: 53001
  maxGeneratedPort: 53023
nsqLookup:
  host: localhost
  port: 4161
nsqProducer:
  host: localhost
  tcpPort: 4150
  httpPort: 4151
periodicScheduler:
  current:
    periodMilli: 11000
  pending:
    periodMilli: 7000
logging:
    level: INFO
    loggers:
      com.vsct.dt: INFO
      fr.vsct.dt.nsq: ERROR
    appenders:
      - type: console
        threshold: INFO
        logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%c] [%t] %logger{5} - %X{code} %msg %n"
        timeZone: UTC
commitTimeout: 10
handledHaproxyRefreshPeriodSecond: 20
